- .github/workflows/publishNpm.yml
- package.json
> ci: add workflow to publish to npm

- src/TextEditor/TextEditor.d.ts
- src/TextEditor/TextEditor.js
- src/constants.ts
- src/items/AppItem.d.ts
- src/items/AppItem.js
- src/items/FileItem.d.ts
- src/items/FileItem.js
- src/items/LinkItem.d.ts
- src/items/LinkItem.js
- src/items/S3FileItem.d.ts
- src/items/S3FileItem.js
- src/items/withCaption.js
- src/utils/itemExtra.js
- yarn.lock
> feat: add captions to items

- src/constants.ts
- src/items/AppItem.d.ts
- src/items/AppItem.js
- src/items/FileItem.d.ts
- src/items/FileItem.js
- src/items/S3FileItem.d.ts
- src/items/S3FileItem.js
> fix: refactor AppItem as Component, reset channel, avoid rendering

- src/Header/Header.d.ts
- src/Header/Header.js
- src/HeaderUserInformation/HeaderUserInformation.d.ts
- src/HeaderUserInformation/HeaderUserInformation.js
- src/HeaderUserInformation/index.d.ts
- src/HeaderUserInformation/index.js
- src/Main/Main.d.ts
- src/Main/Main.js
- src/PermissionedComponent/PermissionedComponent.d.ts
- src/PermissionedComponent/PermissionedComponent.js
- src/PermissionedComponent/index.d.ts
- src/PermissionedComponent/index.js
- src/constants.ts
- src/index.tsx
> feat: add left and right content to header

- src/constants.ts
- src/items/LinkItem.js
> Show Iframe Link

- src/SaveButton/SaveButton.d.ts
- src/SaveButton/SaveButton.js
- src/SaveButton/index.js
- src/TextEditor/TextEditor.js
- src/items/DocumentItem.d.ts
- src/items/DocumentItem.js
- src/items/withCaption.js
> edit: allow edition for documents

- src/items/AppItem.js
> refactor: pass mode to app

- src/ItemIcon/ItemIcon.d.ts
- src/ItemIcon/ItemIcon.js
- src/ItemIcon/index.js
- src/constants.ts
- src/index.tsx
> feat: add item icon

- babel.config.js
- package.json
- rollup.config.js
- yarn.lock
> build: output cjs

- src/constants.ts
- src/items/AppItem.tsx
- src/items/FilePdf.tsx
- src/items/LinkItem.tsx
> refactor: get dynamic height for app, pdf and links

- src/Card/Card.tsx
- src/Card/CardHeader.tsx
- src/Card/index.ts
- src/constants.ts
- src/index.ts
- src/types.ts
> feat: add Card component

- src/items/AppItem.tsx
- src/items/LinkItem.tsx
> refactor: define link and app height

- src/Avatar/Avatar.tsx
- src/Thumbnail/Thumbnail.tsx
- src/constants.ts
> feat: add size in thumbnail and avatar

- src/ItemIcon/ItemIcon.tsx
- src/constants.ts
> refactor: add zip icon

- src/items/AppItem.tsx
> refactor: get request api access token endpoint from prop

- package.json
- src/CookiesBanner/CookiesBanner.tsx
- src/CookiesBanner/index.ts
- src/index.ts
- yarn.lock
> feat: add cookies banner

- src/constants.ts
- src/items/FileAudio.tsx
- src/items/FileImage.tsx
- src/items/FileItem.tsx
- src/items/FilePdf.tsx
- src/items/FileVideo.tsx
- src/items/LinkItem.tsx
- src/items/S3FileItem.tsx
- yarn.lock
It might come in really handy for you @alvrba 
close #100
> refactor: add classname to item components

- src/constants.ts
- src/items/DownloadButton.tsx
- src/items/index.ts
> feat: add download button

- src/Button/Button.tsx
> feat: add dataCy prop to Button

- src/Button/Button.tsx
> refactor: add fullwidth to button

- src/Button/Button.tsx
- src/TableComponent/Table.tsx
> refactor: add component to Button

- .storybook/global.css
- .storybook/preview.js
- package.json
- rollup.config.js
- src/Authorization/withAuthorization.tsx
- src/Button/Button.tsx
- src/Navigation/Navigation.stories.tsx
- src/Navigation/Navigation.tsx
- src/UserSwitch/UserSwitch.tsx
- src/UserSwitch/UserSwitchWrapper.tsx
- src/items/LinkItem.tsx
- src/types.ts
- yarn.lock
This PR updates the Navigation component with renamed Analytics and Library. I've also added the navigation in storybook, and use graasp-sdk.
close #154
> refactor: rename navigation library and analytics

- src/Button/Button.tsx
- src/DynamicTreeView/DynamicTreeView.tsx
- src/items/LinkItem.stories.tsx
- src/items/LinkItem.tsx
- src/types.ts
- src/utils/itemExtra.ts
> feat: add link to storybook, add showIframe and showButton booleans

- .github/workflows/storybook.yml
> refactor: allow manual trigger to deploy storybook

- .github/workflows/publishNpm.yml
- .github/workflows/release-please.yml
- .github/workflows/storybook.yml
This fixes release please to use either master of main until we change the name of the default branch.
> fix: add master branch to trigger workflows

- LICENSE
- package.json
This PR updates the license to use `AGPL-3.0-only` in place of `MIT`.
closes #180
> 180 change license

- package.json
- src/TextEditor/TextEditor.tsx
- src/constants.ts
- yarn.lock
Hello,
I solved it. I got the information from the website https://npm.io/package/quill-emoji. I hope everything goes well and the emoticons work properly.
> Add emoji picker to TextEditor. #166

- src/TextEditor/TextEditor.tsx
- src/constants.ts
- src/items/FileItem.tsx
- src/items/FilePdf.tsx
> 188 pdf viewer constant

- src/items/AppItem.tsx
This PR allow app iframes to request fullscreen mode.
closes #192
> fix: allow fullscreen on app iframes

- .github/workflows/release-please.yml
This PR updates the release-please deployment to use the new composite action from deploy.
closes #196
> fix: update npm publish deployement

- src/hooks/index.ts
- src/hooks/useFullscreen.tsx
- src/index.ts
This PR adds a custom hook to toggle to and from fullscreen mode.
closes #200
> feat: add fullscreen custom hook

- package.json
- src/icons/ItemIcon.tsx
- src/items/EtherpadItem.tsx
- src/items/H5PItem.tsx
- src/items/index.ts
- yarn.lock
- Add iframe etherpad integration
- Improve security of H5P sandboxing (todo: check that H5P still work as expected)
> feat: add etherpad UI components

- src/Main/Main.tsx
- src/Select/Select.tsx
> feat: add handleDrawerOpen and handleDrawerClose to Main

- src/MainMenu/MainMenu.tsx
> feat: add fullHeight prop to MainMenu

- src/PlatformSwitch/PlatformSwitch.tsx
> Revert "fix: clear hover state when platform opens in new tab"

- src/items/AppItem.tsx
> refactor: return lang from member and item in app item

- src/Card/Card.stories.tsx
- src/Card/Card.tsx
- src/Card/CardHeader.tsx
This PR improves the card component.
closes #258
> fix: improve card component and add stories

- README.md
Change license in readme from MIT to AGPL-3.0
closes #269
> docs: update license in readme

- src/Collapse/withCollapse.tsx
- src/itemLogin/ItemLoginAuthorization.tsx
- src/itemLogin/ItemLoginScreen.tsx
- src/items/DocumentItem.tsx
- fix: optional types on ItemLoginSchema
- fix: type of withCollapse comp uses ItemRecord
> 267 improve optional types on itemloginauthorization

- src/constants.ts
- src/items/LinkItem.tsx
This PR adds the DEFAULT_LINK_SHOW_BUTTON constant
> fix: add DEFAULT_LINK_SHOW_BUTTON constant

- src/Card/Card.tsx
- src/TableComponent/Table.tsx
- src/TextEditor/TextEditor.tsx
- src/UserSwitch/UserSwitch.tsx
- src/buttons/FavoriteButton/FavoriteButton.tsx
- src/constants.ts
- src/icons/ItemIcon.tsx
- src/icons/ResizingIcon.tsx
- src/index.ts
- src/itemLogin/ForbiddenText.tsx
- src/itemLogin/ItemLoginScreen.stories.tsx
- src/itemLogin/constants.ts
- src/items/AppItem.tsx
- src/items/FilePdf.tsx
- src/items/ItemSkeleton/ItemSkeleton.tsx
- src/items/LinkItem.tsx
- src/items/constants.ts
- src/items/withCaption.tsx
- src/items/withResizing.tsx
This PR exposes public constants and colocates local constants closer to where they are used.
> fix: export public constants and colocate local constants

- .github/workflows/test.yml
- src/hooks/useFullscreen.tsx
In this PR we make the `useFullScreen` hook update on external fullscreen event changes.
> fix: detect fullscreen changes

- src/items/DocumentItem.tsx
> fix: use precise item type in DocumentItem given showCollapse

- .github/workflows/storybook.yml
This PR fixes the build command used in the storybook workflow. This command was changed in the typeorm refactor PR.
> fix: storybook build command in storybook build workflow

- .github/workflows/storybook.yml
- src/buttons/Button/Button.stories.tsx
- src/buttons/Button/Button.tsx
> feat: adds type to button

- .travis.yml
This PR removes the unused `.travis.yml` file.
> chore(cleanup): remove travis.yml file

- src/PlatformSwitch/hooks.ts
> fix: update analytics url for platform switch

- package.json
- src/hooks/index.ts
- src/hooks/useShortenedURLParams.tsx
- src/utils/utils.ts
- yarn.lock
> feat: custom hook to get uuid url params

- src/Select/Select.tsx
add a `value` props to select as it's uncontrolled now
> feat: add value to select component

- src/UserSwitch/UserSwitch.stories.tsx
- src/UserSwitch/UserSwitch.tsx
- src/UserSwitch/UserSwitchWrapper.tsx
Update `UserSwitchWrapper` to render both liked Items and library profile options conditionally.
> feat: add custom profile option to user dropdown

- package.json
- src/items/FileItem.stories.tsx
- yarn.lock
Ref https://github.com/graasp/graasp-sdk/pull/339
fix #590
> fix: support WebP format

- src/Select/Select.stories.tsx
This PR improves the Select stories.
> fix: propose story enhancements

- src/Select/Select.stories.tsx
- src/Select/Select.tsx
> feat: add disable to select options

- package.json
- src/Authorization/withAuthorization.tsx
- src/UserSwitch/UserSwitchWrapper.tsx
- src/icons/ItemIcon.tsx
- yarn.lock
This `mimetype` option is an alternative to providing the `extra` prop
> feat: add mimetype option in `ItemIcon`

- src/Select/Select.stories.tsx
- src/Select/Select.tsx
> fix: disabled prop issues

- src/itemLogin/ForbiddenContent.stories.tsx
- src/itemLogin/ForbiddenContent.tsx
- src/itemLogin/ForbiddenText.tsx
According to a comment in builder I remove some props here. I checked usage and it looks like the `showPseudonymized` option is not used in Builder nor player.
> fix: update forbiddenContent

- src/Main/Main.tsx
> fix: use `overflow: auto` instead of `overflow: scroll`

- .github/workflows/test.yml
- src/items/withResizing.tsx
In this PR:
I have already set this up in the account repo and it helps to merge PRs faster without having to babysit them.
> chore: add merge queue trigger in workflow

- package.json
- src/items/FileItem.stories.tsx
- src/items/withCaption.tsx
- yarn.lock
This PR refer to graasp/graasp-ui#694.
> feat: update the withCaption stack depending on the desc placement

- src/Main/Main.stories.tsx
- src/Main/Main.tsx
In this PR I propose to add a footer that integrates well with the new main component. This is needed for the library.
> fix: allow to add a footer under main

- src/SearchInput/SearchInput.stories.tsx
- src/SearchInput/SearchInput.tsx
> fix: prevent enter in search

- src/appComponents/ErrorFallback.stories.tsx
- src/buttons/BookmarkButton/BookmarkButton.stories.tsx
- src/buttons/BookmarkButton/BookmarkButton.tsx
- src/buttons/BookmarkButton/index.ts
- src/buttons/FavoriteButton/index.ts
- src/buttons/index.ts
- src/items/index.ts
> feat: rename favorite to bookmark

- .storybook/global.css
- src/TableComponent/Table.tsx
- src/theme.ts
- **fix: comment out font augmentation for now**
- **fix: add table font styles for storybook**
> fix: reduce font size in theme

- src/Collapse/withCollapse.tsx
- src/Main/Main.stories.tsx
- src/Main/Main.tsx
- src/theme.ts
In this PR:
- add `backgroundColor` option for main and drawers
- update usages of name to be displayName where relevant (this is a bit of an issue in some places, comments welcome)
- default to button text using `capitalise` instead of `uppercase`
> fix: propose general improvements related to player

- src/Select/Select.stories.tsx
- src/Select/Select.tsx
- src/ThemeContext/LanguageSelect.tsx
- src/ThemeContext/ThemeContext.stories.tsx
- src/ThemeContext/ThemeContext.tsx
In this PR I remove the margin that is present when there is no label.
> fix: remove margin when there is no label

- src/itemLogin/ItemLoginScreen.tsx
> fix: overflow on item login screen

- src/itemLogin/MemberIdTextField.tsx
- src/items/LinkItem.tsx
- src/items/withCaption.tsx
- src/items/withResizing.tsx
This PR should fix the iframe sizing issue observed on the latest release of ui.
> fix: issue with Iframe sizing

- src/items/AppItem.tsx
- src/items/withResizing.tsx
> fix: unset height when using dynamic resizing

- src/items/AppItem.stories.tsx
- src/items/AppItem.tsx
> fix: add timestamp to app url

- src/Collapse/Collapse.tsx
- src/Collapse/withCollapse.tsx
- src/items/AppItem.tsx
- src/items/DocumentItem.tsx
- src/items/FileItem.tsx
- src/items/H5PItem.tsx
- src/items/LinkItem.tsx
> feat: add `onCollapse` handler

- package.json
- yarn.lock
This PR uses the new sdk branch for the changes in the backend https://github.com/graasp/graasp/pull/1131
> feat: update package

- src/items/DownloadButtonFileItem.stories.tsx
- src/items/DownloadButtonFileItem.tsx
- src/items/FileItem.tsx
> fix: improve downloadButton

- src/itemLogin/ItemLoginWrapper.stories.tsx
- src/itemLogin/ItemLoginWrapper.tsx
Check item error code status to show request access.
> fix: show request access on forbidden only

- src/theme.ts
In this PR: 
- fix the colour of outlined inputs
> fix: add outlined input background color

- package.json
- src/ItemFlag/ItemFlagDialog.stories.tsx
- src/MainMenu/MenuItem/MenuItem.stories.tsx
- src/Navigation/Navigation.stories.tsx
- src/PlatformSwitch/PlatformSwitch.stories.tsx
- src/Select/Select.stories.tsx
- src/Tree/Breadcrumbs.stories.tsx
- src/Tree/RowMenu.stories.tsx
- src/Tree/RowMenus.stories.tsx
- src/UserSwitch/UserSwitch.stories.tsx
- src/UserSwitch/UserSwitchWrapper.stories.tsx
- src/buttons/BookmarkButton/BookmarkButton.stories.tsx
- src/buttons/ChatboxButton/ChatboxButton.stories.tsx
- src/buttons/DownloadButton/DownloadButton.stories.tsx
- src/buttons/EditButton/EditButton.stories.tsx
- src/buttons/PinButton/PinButton.stories.tsx
- src/buttons/ShareButton/ShareButton.stories.tsx
- src/itemLogin/ItemLoginScreen.stories.tsx
- src/itemLogin/ItemLoginWrapper.stories.tsx
- src/items/AppItem.stories.tsx
- src/upload/FileDropper/FileDropper.stories.tsx
- src/upload/UploadFileButton/UploadFileButton.stories.tsx
- yarn.lock
In this PR: 
- remove `@storybook/testing-library` package
- use unified `@storybook/test` package instead
> fix: remove testing library addon and use unified testing package for storybook

- src/CookiesBanner/CookiesBanner.tsx
- src/Main/Main.stories.tsx
https://github.com/user-attachments/assets/61f759db-529d-4fa9-832f-d8054eb4d93b
> fix: cookie buttons

- src/CookiesBanner/CookiesBanner.stories.tsx
- src/CookiesBanner/CookiesBanner.tsx
> fix: cookie banner

- src/theme.ts
In this PR:
- add a global style override for scrolling behaviour
> fix: add smooth scroll

- src/Thumbnail/Thumbnail.tsx
These changes will be used by Cards in Library.
> feat: add sizing properties to Thumbnail

- src/icons/LibraryIcon.tsx
Allow library icon to be disabled
> fix: library icon can be disabled
