src/TextEditor/TextEditor.tsx
src/constants.ts
src/items/DocumentItem.tsx

This PR added more headings, and fonts for the text editor (request from Gilles).
close #78 
close https://github.com/graasp/graasp-ui/issues/77

feat: add more headings and fonts for text editor

---

.github/workflows/release-please.yml

This PR adds release-please to create versions of the package with support for GitHub releases.
Releases are managed trough PRs that are automatically kept up to date with un-released commits on the default branch.
closes #173

chore(ci): add release please with npm publish integration

---

src/items/H5PItem.tsx

H5P cannot be displayed anymore since last update of H5P iframes (the origin of the iframe is now null because of the sandbox)

fix: revert to default iframe

---

src/PlatformSwitch/PlatformSwitch.tsx

Fixes a bug where the hover state could not be cleared when a platform was opened in a new tab

fix: clear hover state when platform opens in new tab

---

src/constants.ts
src/items/FileAudio.stories.tsx
src/items/FileAudio.tsx
src/items/FileItem.stories.tsx

Currently audio files in WAV format are shown as the default file (download button)  while they could be played in the browser.
Adding the MIME type will allow the files to be displayed as an audio file and played directly.
closes #255

feat: support wav as audio format

---

src/buttons/DeleteButton/DeleteButton.tsx
src/buttons/FavoriteButton/FavoriteButton.stories.tsx
src/buttons/FavoriteButton/FavoriteButton.tsx
src/buttons/MoveButton/MoveButton.stories.tsx
src/buttons/MoveButton/MoveButton.tsx
src/buttons/PinButton/PinButton.stories.tsx
src/buttons/PinButton/PinButton.tsx
src/constants.ts
src/types.ts

This PR uniformises the use of the `ButtonTypeEnum` and removes the `BUTTON_TYPE` object.
closes #257

257 use buttontypeenum

---

src/PlatformSwitch/PlatformSwitch.tsx

This PR should fix the react error about missing key in list.
closes #265

fix: add key to list element in platform switch

---

src/Avatar/Avatar.tsx
src/Card/Card.tsx
src/Card/CardHeader.tsx
src/items/ItemSkeleton/ItemSkeleton.tsx

This PR updates the default skeleton shape value for the `Avatar` component.
closes #263

fix: set default skeleton variant to circular for Avatar

---

package.json
src/Thumbnail/Thumbnail.tsx
src/constants.ts
src/icons/ItemIcon.stories.tsx
src/icons/ItemIcon.tsx
src/items/FileAudio.stories.tsx
src/items/FileItem.stories.tsx
src/items/FileItem.tsx
src/items/S3FileItem.tsx
src/types.ts
yarn.lock

This PR uses sdk verion `0.8.0` and updates the usage of `MIME_TYPES` and `ThumbnailSize` to the ones provided by sdk.
closes #273

fix: use MimeTypes and ThumbnailSize from sdk

---

src/Card/Card.stories.tsx
src/Card/Card.tsx
src/ItemBadges/ItemBadges.stories.tsx
src/ItemBadges/ItemBadges.tsx
src/ItemBadges/index.ts
src/TableComponent/Table.stories.tsx
src/TableComponent/Table.tsx
src/constants.ts
src/index.ts

This PR adds a new component `ItemBadges` that displays hidden, published, public and pinned status of items.
This Component can be used on the Card component as seen below:

282 display item badges on card

---

src/Header/Header.stories.tsx
src/Header/Header.tsx
src/Main/Main.tsx
src/theme.ts

Closes #278 
This PR adds the platform-specific colors to the header appbar.
[Peek 2023-03-10 11-12.webm](https://user-images.githubusercontent.com/14943421/224292651-9cf86b56-45a7-4fa9-a12b-e820c42985e4.webm)

feat: add header platform colors

---

src/icons/EtherpadIcon.stories.tsx
src/icons/EtherpadIcon.tsx
src/icons/ItemIcon.tsx
src/icons/index.ts

Closes #276 
This PR adds the etherpad logo as a SVG-in-JSX component which replaces the previously used `GroupsIcon`.

feat: add etherpad logo

---

src/SearchInput/SearchInput.stories.tsx
src/SearchInput/SearchInput.tsx

This PR updates the search bar to be able to compress (minWidth:0) and the 
`width` parameter can now be used to set a `maxWidth`. Otherwise he bar will always 
take the space available in its parent.

fix: search bar can be compressed and is responsive

---

src/icons/EtherpadIcon.tsx

fix: etherpad icon use current color as default

---

src/ItemBadges/ItemBadges.tsx

This PR fixes the ItemBadges color to be more present.

fix: use a darker color for itemBadges

---

src/icons/LibraryIcon.stories.tsx
src/icons/LibraryIcon.tsx

This PR adds a prop to show the library icon with a setting cog:

feat: add library icon setting cog option

---

src/ItemBadges/ItemBadges.stories.tsx
src/ItemBadges/ItemBadges.tsx
src/buttons/CopyButton/CopyButton.tsx
src/buttons/MoveButton/MoveButton.tsx

This PR adds the `isCollapsible` and `showCahtbox` statuses to the item badges.
closes #309

fix: add collapsible and chat to itemstatus

---

src/TableComponent/Table.tsx

This PR adds a style on the `.ag-cell-wrapper` to ensure that custom cell renderers do not overflow the width of the cell if they use flex containers.
Currently:
With the fix:

fix: add constraint for custom cell renderers

---

package.json
yarn.lock

Linked to graasp/graasp-builder#660
closes #369

fix(deps): revert react-quill to 2.0.0-beta.4

---

src/HeaderUserInformation/HeaderUserInformation.tsx
src/UserSwitch/UserSwitch.stories.tsx
src/UserSwitch/UserSwitch.tsx
src/utils/fixtures.ts

Closes #362 
Adds role button to the profile wrapper working as a button in the `UserSwitch`. As well as aria-attributes used for pop-up menus. 
Also adds this to `HeaderUserInformation` so this could be used in `UserSwitch` later (I didn't do it now since I can't test so everything works as it should in Builder etc). 
I've added a mock user of memberRecord type, however I don't know if this should be in fixtures. I didn't add any argTypes to the story, since I don't know what they should be. 
Could also be an idea to set an aria-hidden on the tooltip when the text for it is the username, since otherwise the username is read out twice by screen readers. However this would also hide the profile image from the accessibility tree, so it's a bit of a trade off.

362 add button role profile wrapper header

---

src/items/FileItem.tsx

In the previous implementation, the mimetype was undefined when the extra were of Immutable type. This was because the spread syntax was not working on immutable records. 
We fixed it by simply converting the extra to JS.

fix: mimetype is undefined when items are immutable

---

src/items/FileItem.tsx

The `altText` should default to the item name when it is `undefined` or `''`. This is not the best but at least assistive technologies will not skip it.

fix(a11y): use item name when alttext is falsy

---

rollup.config.js

This PR fixes an issue in the latest release.
The `bundle.css` was not emmited because of the update of the `rollup-plugin-scss` dependency.
This fixes this issue and the bundle.css is not succesfully emitted.

fix: replace `output` by `fileName` in rollup-plugin-scss options

---

src/UserSwitch/UserSwitchWrapper.stories.tsx
src/UserSwitch/UserSwitchWrapper.tsx

I've enabled back the "sign out" menu item that was missing. 
I've added some simple visual tests for `UserSwitch` and `UserSwitchWrapper`.
close #440

fix: show sign out in user switch

---

src/TextEditor/TextEditor.tsx

In this PR we fix an issue related to the `z-index` property on the elements in the Quill Text Editor.
When opening the link tool, the popup that appears is **under** the "Cancel" and "Save" buttons. 
Set a `z-index` higher than the z-index of the buttons. We can use [the z-index from MUI](https://mui.com/material-ui/customization/z-index/) and select a suitable value like `tooltip`.

fix: zIndex on quill tooltip

---

package.json
src/Select/Select.tsx
src/ThemeContext/LanguageSelect.tsx
src/ThemeContext/ThemeContext.stories.tsx
src/ThemeContext/ThemeContext.tsx
src/ThemeContext/index.ts
src/index.ts
src/types.ts
yarn.lock

The `ThemeContext` provides the theme + direction support, and returns a language select to be displayed wherever you want in the interface. 
close #472

feat: add ThemeContext with rtl support

---

package.json
src/Collapse/withCollapse.tsx
src/items/AppItem.tsx
src/items/DocumentItem.tsx
src/items/FileImage.tsx
src/items/FileItem.stories.tsx
src/items/FileItem.tsx
src/items/FilePdf.stories.tsx
src/items/H5PItem.tsx
src/items/LinkItem.tsx
src/items/withCaption.tsx
yarn.lock

`FileItem` is updated to add a container with a `maxWidth` property.
Default is `xl`.
The best would be to center the image, but it's not really clear because of the description. I've opted for a left align, to keep the description always full sized.
Let me know if you prefer to center, and have an ugly look for small images (small image is centered, but the description is align left). It might be better that way, to enforce bigger images? 
close #503

503 resize file

---

src/buttons/DownloadButton/DownloadButton.stories.tsx
src/buttons/DownloadButton/DownloadButton.tsx

I'll use this to add the download button in the item menu in builder instead of in the "header".

feat: add download button menu item

---

package.json
src/Header/Header.tsx
src/Main/Main.tsx
src/theme.ts
yarn.lock

This PR updates:
- sdk to 2.1.0 (with account in `Context`) and necessary changes for types to work a little better

fix: allow better typing for Context enum and add color for account

---

src/Select/Select.stories.tsx
src/Select/Select.tsx

This PR adds a `disabled` prop on the select to completely disable the select:

fix: add a disabled prop to the select

---

src/Navigation/CurrentItemNavigation.tsx
src/Navigation/ExtraItemsMenu.tsx
src/Navigation/ExtraItemsNavigation.tsx
src/Navigation/ItemActionsMenu.tsx
src/Navigation/ItemMenu.tsx
src/Navigation/Navigation.stories.tsx
src/Navigation/Navigation.tsx
src/Navigation/ParentsNavigation.tsx

Add an extra props for navigation component to accept extraItems, Basically `extraItems` has the following structure
```
[
{
name: "",
path?: "",
Icon?: ,
menuItems?: [
{
name: "",
path: ""
}
]
}
]
```
closes #686

feat: navigator render extra item

---

src/icons/ItemIcon.stories.tsx
src/icons/ItemIcon.tsx

In this PR:
- use the `sx` prop passe when displaying the `iconSrc`
- remove deprecated props

fix: use sx prop passed when there is an src

---

CHANGELOG.md
package.json
src/Collapse/Collapse.stories.tsx
src/ItemBadges/ItemBadges.tsx
src/Navigation/Navigation.stories.tsx
src/buttons/ChatboxButton/ChatboxButton.stories.tsx
src/buttons/ChatboxButton/ChatboxButton.tsx
src/buttons/CopyButton/CopyButton.stories.tsx
src/buttons/CopyButton/CopyButton.tsx
src/buttons/DeleteButton/DeleteButton.tsx
src/buttons/DownloadButton/DownloadButton.tsx
src/buttons/EditButton/EditButton.tsx
src/buttons/FavoriteButton/FavoriteButton.stories.tsx
src/buttons/FavoriteButton/FavoriteButton.tsx
src/buttons/MenuItemButton.tsx
src/buttons/MoveButton/MoveButton.tsx
src/buttons/PinButton/PinButton.stories.tsx
src/buttons/PinButton/PinButton.tsx
src/buttons/ShareButton/ShareButton.tsx
src/items/AppItem.stories.tsx
src/items/FileItem.stories.tsx
src/items/LinkItem.stories.tsx
src/types.ts
yarn.lock

This PR refactors the icon buttons:
- factor out a generic item menu component
- adds item menu variant to some buttons
- add the ICON variant, that returns only the corresponding icon without IconButton

feat: update buttons

---

src/TableComponent/Table.tsx

In this PR I add a style to properly hide the `aria-description` that is displayed when dragging elements in the table. It should be hidden visually but accessible to screen readers. It looks like we do not get the required styles when importing it in the builder. I provide the style as CSS in JSX directly here.

fix: add styles on table to hide aria-description

---

src/items/withCaption.tsx

fix: wrap component inside Box in withCaption to solve image height

---

src/Card/Card.tsx

In this PR:
- allow to use a component as the card description

fix: allow component as card description

---

src/CreativeCommons/CreativeCommons.tsx

fix: decrease cclicence tooltip size

---

src/TextDisplay/withFlavor.tsx

Allow to show the title on a DocumentItem more prominently
Before:
After:

fix: update alert title

---

.github/workflows/test.yml

It looks like when playwright is added from the cache the test complain because there is something missing. So in this PR I install playwright both if the cache is found and if it is missing. Hopefully this fixes the issue.

fix: playwright install issue

---

src/TableComponent/Table.tsx

https://github.com/graasp/graasp-ui/assets/147397675/1e606fdf-e29e-4906-9caf-70487d59c44d
In this video, the hide/show action is not rerender when the items in the table changed. I fix it quickly because we will change the table soon.

fix: quick fix rerender of column defs

---

src/items/H5PItem.tsx

Some h5p provide fullscreen feature. Before the fix it resized once and stays like this, it's impossible to revert.
https://github.com/graasp/graasp-ui/assets/11229627/eda5ac7f-83ea-48c9-afc5-05a0e5188a34
I added the `allowFullscreen` prop for the iframe.
It does not work perfectly, one click over three resize weirdly. 
Without this change, the fullscreen does not work at all, so I guess it's okay as compromise.
I quickly tried to set `height=100%` on fullscreen event, but it didn't work.
https://github.com/graasp/graasp-ui/assets/11229627/09f9ebba-74be-4759-80d8-acf84dd31ff5

fix: allow fullscreen for h5p iframe

---

src/items/withResizing.tsx

In this PR I remove the maxHeight of 70vh on the app iframe.
This code has been used in builder and player and deployed to test the effect. It works as expected for automatic height apps.

fix: remove max-height

---

package.json
src/items/FileAudio.tsx
src/items/FileItem.stories.tsx
src/items/FileItem.tsx
src/items/SizingWrapper.tsx
src/items/withCaption.tsx
yarn.lock

In this PR:
- drop `sx` prop from FileItem
- drop `showCaption` prop from FileItem
- make `audio` full-width
- default sizing to full-width
- default alignement to center for content that has a known mimetype, other mimetypes that display as button are left-aligned
- add alignment conversion function from SDK back here
- export a captionWrapper as a simple component, keep the possibility of usign it as an HOC

fix: allow container to take full-width

---

src/theme.ts

In this PR, I update the theme overrides in order for the helper text of the Textfield to be on the transparent background instead of the ugly white.

fix: theme overrides so helper text is not on white background

---

src/Card/Card.stories.tsx
src/Card/Card.tsx
src/Card/CardHeader.tsx
src/Card/CardThumbnail.tsx
src/Card/Cards.stories.tsx
src/Card/FolderCard.tsx
src/buttons/Button/Button.tsx
src/draggable/DraggableElement.tsx
src/draggable/DraggingWrapper.stories.tsx
src/draggable/DraggingWrapper.tsx
src/draggable/InBetween.tsx
src/draggable/types.ts
src/index.ts
yarn.lock

This PR adds `DraggingWrapper` to allow moving and dropping elements in other elements. I changed the cards for updated item table layout.

feat: add draggable elements, to replace table

---

.storybook/preview.tsx
src/ThemeContext/ThemeContext.tsx
src/theme.ts

feat: add a theme direction

---

src/index.ts

add missing export for `useButtonColor` hook

fix: add buttonColor hook

---

src/buttons/PinButton/PinButton.tsx

The icon was not following the logic of the text.
The icon and the text are describing the next action.

fix: reverse pin icon

---

src/TextEditor/TextEditor.stories.tsx
src/TextEditor/TextEditor.tsx
src/TextEditor/TextEditorWrapper.stories.tsx

This PR fixes a very sneaky bug with the unusual behaviour of the `placeholder` prop from react-quill.
I have added an interaction test that ensures that the placeholder can be updated.
fix #1049

fix: quill placeholder does not update

---

src/Card/Card.tsx

ref https://github.com/graasp/graasp-builder/issues/1433
The solution is to keep track of cards, which is done through a class for dense cards, but not non-dense cards.

fix: pass classname to dense card

---

src/Main/Main.stories.tsx
src/Main/Main.tsx

In this PR:
- update the type of the children prop to `ReactNode` to allow all possible valid react elements to be a children
- add some umami tags for use in builder

fix: children type and umami-tags

---

src/Main/Main.tsx

This fixes a small bug where the footer of the `Main` component was using a `main` html tag instead of a `footer` tag.

fix: footer should use footer html tag

---

src/buttons/DownloadButton/DownloadButton.tsx
src/constants.ts

https://github.com/user-attachments/assets/691208b2-5e7a-4dc9-8812-77d0dc65a39f
https://github.com/user-attachments/assets/88b2729d-b3cd-48b2-b37a-3fc4ca3c0fd6

fix: download button colour and loader behaviour

---

src/theme.ts

This PR fixes the scroll behaviour. It was supposed to be set on the `html` element to work correctly.

fix: scroll behavior

---

src/apps.ts

In this PR I add the `useFullscreen` hook to the apps bundle so it can be used without errors if you do not have the required dependencies.

fix: add useFullscreen hook in apps bundle
